### ISSUE TITLE
`NoSuchMethodError` on specs2 test using `CatsEffect` trait

### ISSUE THREAD

**Issue by LLCampos** [djspiewak/cats-effect-testing#229]
Hi!

Here's something I've found while doing dependency upgrades:

```scala
scalaVersion := "2.13.7"

libraryDependencies ++= Seq(
  "org.typelevel" %% "cats-effect" % "3.2.8",
  "org.specs2" %% "specs2-core" % "4.13.0" %  Test,
  "org.typelevel" %% "cats-effect-testing-specs2" % "1.3.0" % Test,
)
```

```scala
import cats.effect.IO
import cats.effect.testing.specs2.CatsEffect
import org.specs2.mutable.SpecificationLike

class CatsEffectSpecs extends CatsEffect with SpecificationLike {
  "test" should {
    "test" in {
      IO(ok)
    }
  }
}
```

The above fails with:

```
Exception in thread "specs2-3" java.lang.NoSuchMethodError: 'org.specs2.specification.core.Execution org.specs2.specification.core.Execution.copy(scala.Option, org.specs2.specification.core.Executing, scala.Option, boolean, scala.Function1, boolean, scala.Option, scala.Option)'
        at cats.effect.testing.specs2.CatsEffect$$anon$1.execute(CatsEffect.scala:40)
        at org.specs2.specification.dsl.mutable.ExampleDsl0$BlockExample0.$greater$greater(ExampleDsl.scala:84)
        at org.specs2.specification.dsl.mutable.ExampleDsl0$BlockExample0.in(ExampleDsl.scala:100)
        at CatsEffectSpecs.$anonfun$new$1(CatsEffectSpecs.scala:7)
        at org.specs2.specification.dsl.mutable.EffectBlocks.tryBlock(EffectBlocks.scala:131)
        at org.specs2.specification.dsl.mutable.EffectBlocks.$anonfun$nestBlock$2(EffectBlocks.scala:110)
        at org.specs2.specification.dsl.mutable.EffectBlocks.record(EffectBlocks.scala:61)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder.$anonfun$replayFragments$2(MutableFragmentBuilder.scala:47)
        at scala.Option.getOrElse(Option.scala:201)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder.replayFragments(MutableFragmentBuilder.scala:47)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder.specificationFragments(MutableFragmentBuilder.scala:37)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder.specificationFragments$(MutableFragmentBuilder.scala:36)
        at CatsEffectSpecs.specificationFragments(CatsEffectSpecs.scala:5)
        at org.specs2.specification.dsl.mutable.MutableFragmentBuilder.$anonfun$is$1(MutableFragmentBuilder.scala:44)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.$anonfun$map$1(SpecStructure.scala:29)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.$anonfun$$bar$greater$1(SpecStructure.scala:30)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.$anonfun$$bar$greater$1(SpecStructure.scala:30)
        at org.specs2.specification.core.SpecStructure.fragments$lzycompute(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.fragments(SpecStructure.scala:26)
        at org.specs2.specification.core.SpecStructure.contents(SpecStructure.scala:28)
        at org.specs2.reporter.Reporter.$anonfun$report$1(Reporter.scala:43)
        at org.specs2.runner.Runner$.runSpecStructure(Runner.scala:109)
        at org.specs2.runner.SbtTask.$anonfun$specificationRun$1(SbtRunner.scala:183)
        at org.specs2.control.eff.Arrs.go$1(Eff.scala:380)
        at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
        at org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:198)
        at org.specs2.control.eff.Arrs.go$1(Eff.scala:380)
        at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
        at org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
        at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
        at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
        at org.specs2.control.eff.Arrs.apply(Eff.scala:348)
        at org.specs2.control.eff.CollectedUnions.$anonfun$continuation$1(Unions.scala:84)
        at org.specs2.control.eff.Arrs.go$1(Eff.scala:380)
        at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
        at org.specs2.control.eff.Interpret$$anon$1.$anonfun$onEffect$1(Interpret.scala:53)
        at org.specs2.fp.EitherOps$.bimap$extension(EitherSyntax.scala:82)
        at org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:53)
        at org.specs2.control.eff.Interpret$$anon$1.onApplicativeEffect(Interpret.scala:61)
        at org.specs2.control.eff.Interpret$$anon$1.onApplicativeEffect(Interpret.scala:45)
        at org.specs2.control.eff.Interpret.go$1(Interpret.scala:200)
        at org.specs2.control.eff.Interpret.interpretLoop(Interpret.scala:207)
        at org.specs2.control.eff.Interpret.interpretLoop$(Interpret.scala:142)
        at org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:635)
        at org.specs2.control.eff.Interpret.interpret(Interpret.scala:71)
        at org.specs2.control.eff.Interpret.interpret$(Interpret.scala:44)
        at org.specs2.control.eff.Interpret$.interpret(Interpret.scala:635)
        at org.specs2.control.eff.Interpret.interpret1(Interpret.scala:78)
        at org.specs2.control.eff.Interpret.interpret1$(Interpret.scala:77)
        at org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:635)
        at org.specs2.control.eff.ErrorInterpretation.runError(ErrorEffect.scala:87)
        at org.specs2.control.eff.ErrorInterpretation.runError$(ErrorEffect.scala:68)
        at org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:187)
        at org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:14)
        at org.specs2.control.ExecuteActions.executeActionFuture(ExecuteActions.scala:36)
        at org.specs2.control.ExecuteActions.executeActionFuture$(ExecuteActions.scala:31)
        at org.specs2.control.ExecuteActions$.executeActionFuture(ExecuteActions.scala:93)
        at org.specs2.runner.SbtTask.$anonfun$executeFuture$3(SbtRunner.scala:146)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rossabaker** [comment]
It looks like that version is built on specs2-4.12.  Is 4.13 not binary compatible with 4.12?

**Comment by LLCampos** [comment]
Ah, you're right! I looked at the wrong commit when checking what was the current `specs2` version used by `cats-effect-testing` :man_facepalming:
